#!/usr/bin/env python3
"""Build a reproducible Perry Island test slice from the local WOSA assets."""

from __future__ import annotations

import argparse
import shutil
import xml.etree.ElementTree as ET
from pathlib import Path


def lua_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--wosa", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--radius", type=float, default=300.0)
    parser.add_argument("--full", action="store_true", help="include the complete novailhb zone and its stock GTA objects")
    args = parser.parse_args()

    source = args.wosa / "[main]" / "[sl-maps]" / "out"
    zones = source / "zones"
    map_root = ET.parse(zones / "novailhb" / "novailhb.map").getroot()
    definitions = {
        element.attrib["id"]: element.attrib
        for element in ET.parse(zones / "novailha" / "novailha.definition").getroot()
    }

    center_x = 590.629883
    center_y = -144.106003
    translation_x = 8409.370117
    def is_selected(element: ET.Element) -> bool:
        if args.full:
            return True
        return (
            abs(float(element.attrib.get("posX", 0.0)) - center_x) <= args.radius
            and abs(float(element.attrib.get("posY", 0.0)) - center_y) <= args.radius
        )

    placements = [
        element.attrib
        for element in map_root
        if element.attrib.get("id") in definitions
        and is_selected(element)
    ]
    native_objects = [element.attrib for element in map_root if element.attrib.get("id") not in definitions and is_selected(element)]
    model_names = sorted(
        {placement["id"] for placement in placements},
        key=lambda name: (not name.lower().startswith("lod"), name),
    )
    texture_names = sorted({definitions[name]["txd"] for name in model_names})

    assets = args.output / "assets"
    if assets.exists():
        shutil.rmtree(assets)
    assets.mkdir(parents=True)

    asset_files: list[str] = []
    for texture_name in texture_names:
        source_file = source / "textures" / f"{texture_name}.txd"
        destination = assets / source_file.name
        shutil.copy2(source_file, destination)
        asset_files.append(f"assets/{destination.name}")

    for model_name in model_names:
        for extension in ("dff", "col"):
            source_file = zones / "novailha" / extension / f"{model_name}.{extension}"
            destination = assets / source_file.name
            shutil.copy2(source_file, destination)
            asset_files.append(f"assets/{destination.name}")

    data_lines = [
        "-- Generated by utils/extended-world/build_perry_slice.py.",
        f"PERRY_SLICE_TRANSLATION_X = {translation_x:.6f}",
        f"PERRY_SLICE_RADIUS = {args.radius:.1f}",
        f"PERRY_SLICE_FULL = {'true' if args.full else 'false'}",
        "PERRY_SLICE_MODELS = {",
    ]
    for model_name in model_names:
        definition = definitions[model_name]
        alpha = "true" if "alpha" in model_name.lower() else "false"
        data_lines.append(
            "    { name = %s, txd = %s, lodDistance = %s, alpha = %s },"
            % (
                lua_string(model_name),
                lua_string(definition["txd"]),
                definition.get("lodDistance", "299"),
                alpha,
            )
        )
    data_lines.extend(("}", "PERRY_SLICE_PLACEMENTS = {"))
    selected_names = set(model_names)
    for placement in placements:
        lod_parent = placement.get("lodParent")
        if lod_parent not in selected_names:
            lod_parent = None
        data_lines.append(
            "    { model = %s, x = %.6f, y = %.6f, z = %.6f, rx = %.6f, ry = %.6f, rz = %.6f%s },"
            % (
                lua_string(placement["id"]),
                float(placement.get("posX", 0.0)) + translation_x,
                float(placement.get("posY", 0.0)),
                float(placement.get("posZ", 0.0)),
                float(placement.get("rotX", 0.0)),
                float(placement.get("rotY", 0.0)),
                float(placement.get("rotZ", 0.0)),
                f", lodParent = {lua_string(lod_parent)}" if lod_parent else "",
            )
        )
    data_lines.extend(("}", "PERRY_SLICE_NATIVE_OBJECTS = {"))
    for placement in native_objects:
        data_lines.append(
            "    { model = %s, x = %.6f, y = %.6f, z = %.6f, rx = %.6f, ry = %.6f, rz = %.6f },"
            % (
                lua_string(placement["id"]),
                float(placement.get("posX", 0.0)) + translation_x,
                float(placement.get("posY", 0.0)),
                float(placement.get("posZ", 0.0)),
                float(placement.get("rotX", 0.0)),
                float(placement.get("rotY", 0.0)),
                float(placement.get("rotZ", 0.0)),
            )
        )
    data_lines.extend(("}", ""))
    (args.output / "slice_data.lua").write_text("\n".join(data_lines), encoding="utf-8")

    meta_lines = [
        "<meta>",
        '    <info author="MTA Neon" name="Extended World Perry Island slice" type="script" version="2.0.0" />',
        '    <script src="server.lua" type="server" />',
        '    <script src="slice_data.lua" type="client" cache="false" />',
        '    <script src="client.lua" type="client" cache="false" />',
    ]
    meta_lines.extend(f'    <file src="{path}" />' for path in sorted(asset_files))
    meta_lines.extend(("</meta>", ""))
    (args.output / "meta.xml").write_text("\n".join(meta_lines), encoding="utf-8")

    print(
        f"Generated {len(placements)} custom placements, {len(native_objects)} stock objects, "
        f"{len(model_names)} models, {len(texture_names)} TXDs in {args.output}"
    )


if __name__ == "__main__":
    main()
