#!/usr/bin/env node

/**
 * Build the Vice City and Liberty City radar resources from GTA Underground's
 * 96x96 radar grid. Liberty is resampled because its map resource translates
 * the original IPL geometry by -700 world units on X, which is not aligned to
 * the 500-unit native radar cells.
 */

import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

const SOURCE_GRID_SIZE = 96;
const SOURCE_WORLD_MIN = -24000;
const DESTINATION_WORLD_MIN = -10000;
const CELL_WORLD_SIZE = 500;
const TILE_SIZE = 256;
const PIXEL_WORLD_SIZE = CELL_WORLD_SIZE / TILE_SIZE;

const MAPS = {
    bw: {
        resourceName: "ug-bw",
        manifestName: "UG_BW_RADAR_TILES",
        translationX: -16500,
        translationY: -6500,
        columns: [1, 5],
        rows: [3, 5],
        directCopy: true,
    },
    vc: {
        resourceName: "ug-vc",
        manifestName: "UG_VC_RADAR_TILES",
        translationX: 0,
        translationY: 0,
        columns: [30, 37],
        rows: [30, 39],
        directCopy: true,
    },
    lc: {
        resourceName: "ug-lc",
        manifestName: "UG_LC_RADAR_TILES",
        translationX: -700,
        translationY: 0,
        columns: [31, 39],
        rows: [0, 8],
        directCopy: false,
    },
};

function parseArguments() {
    const options = {};
    for (let index = 2; index < process.argv.length; index += 2) {
        const name = process.argv[index];
        const value = process.argv[index + 1];
        if (!name?.startsWith("--") || value === undefined) {
            throw new Error("usage: build_ug_radar.mjs --source DIR --repo DIR --txd-tools DIR");
        }
        const key = name.slice(2);
        options[key] = key === "map" ? value : resolve(value);
    }
    for (const name of ["source", "repo", "txd-tools"]) {
        if (!options[name]) {
            throw new Error(`missing --${name}`);
        }
    }
    if (options.map && !MAPS[options.map]) {
        throw new Error(`unknown --map ${options.map}`);
    }
    return options;
}

function sourceIndex(column, row) {
    return row * SOURCE_GRID_SIZE + column;
}

function sourcePath(sourceDirectory, column, row) {
    return join(sourceDirectory, `radar${sourceIndex(column, row)}.txd`);
}

function sourceCellForDestination(column, row, translationX, translationY) {
    const destinationX = DESTINATION_WORLD_MIN + column * CELL_WORLD_SIZE;
    const destinationTopY = -DESTINATION_WORLD_MIN - row * CELL_WORLD_SIZE;
    const sourceX = destinationX - translationX;
    const sourceTopY = destinationTopY - translationY;
    return {
        column: Math.floor((sourceX - SOURCE_WORLD_MIN) / CELL_WORLD_SIZE),
        row: Math.floor((-SOURCE_WORLD_MIN - sourceTopY) / CELL_WORLD_SIZE),
    };
}

function writeManifest(resource, map, tiles) {
    const lines = [
        "-- Generated by utils/extended-world/build_ug_radar.mjs.",
        `${map.manifestName} = {`,
    ];
    for (const tile of tiles) {
        lines.push(
            `    { path = "${tile.path}", column = ${tile.column}, row = ${tile.row}, source = "${tile.source}" },`,
        );
    }
    lines.push("}", "");
    writeFileSync(join(resource, "radar_tiles.lua"), lines.join("\n"));
}

function updateMeta(resource, tiles) {
    const metaPath = join(resource, "meta.xml");
    let text = readFileSync(metaPath, "utf8");
    const radarScript = '    <script src="radar_tiles.lua" type="client" cache="false" />';
    if (!text.includes(radarScript)) {
        const anchor = '    <script src="map_data.lua" type="client" cache="false" />';
        if (!text.includes(anchor)) {
            throw new Error(`cannot find map_data.lua declaration in ${metaPath}`);
        }
        text = text.replace(anchor, `${anchor}\n${radarScript}`);
    }

    const lines = text.split(/\r?\n/).filter((line) => !line.includes('<file src="assets/radar/'));
    const closingIndex = lines.indexOf("</meta>");
    if (closingIndex < 0) {
        throw new Error(`cannot find </meta> in ${metaPath}`);
    }
    lines.splice(closingIndex, 0, ...tiles.map((tile) => `    <file src="${tile.path}" />`));
    writeFileSync(metaPath, `${lines.join("\n")}\n`);
}

function pixelFromTile(tile, x, y) {
    const offset = (y * TILE_SIZE + x) * 4;
    return [tile[offset], tile[offset + 1], tile[offset + 2], tile[offset + 3]];
}

function interpolate(left, right, amount) {
    return left.map((value, index) => Math.round(value + (right[index] - value) * amount));
}

async function buildMap(options, key, map, TXDReader, TXDWriter) {
    const resource = join(options.repo, "test-resources", map.resourceName);
    const radarDirectory = join(resource, "assets", "radar");
    rmSync(radarDirectory, { recursive: true, force: true });
    mkdirSync(radarDirectory, { recursive: true });

    const decodedTiles = new Map();
    function loadSource(column, row) {
        const cacheKey = `${column},${row}`;
        if (decodedTiles.has(cacheKey)) {
            return decodedTiles.get(cacheKey);
        }
        const path = sourcePath(options.source, column, row);
        if (!existsSync(path)) {
            throw new Error(`missing source radar tile ${path}`);
        }
        const input = readFileSync(path);
        const arrayBuffer = input.buffer.slice(input.byteOffset, input.byteOffset + input.byteLength);
        const texture = new TXDReader().parse(arrayBuffer).textures[0];
        if (!texture?.imageData || texture.width !== TILE_SIZE || texture.height !== TILE_SIZE) {
            throw new Error(`invalid source radar texture ${path}`);
        }
        decodedTiles.set(cacheKey, texture.imageData);
        return texture.imageData;
    }

    const tiles = [];
    for (let row = map.rows[0]; row <= map.rows[1]; row++) {
        for (let column = map.columns[0]; column <= map.columns[1]; column++) {
            const sourceCell = sourceCellForDestination(
                column,
                row,
                map.translationX,
                map.translationY,
            );
            const relative = `assets/radar/tile_${String(column).padStart(2, "0")}_${String(row).padStart(2, "0")}.txd`;
            const output = join(resource, relative);

            if (map.directCopy) {
                const input = sourcePath(options.source, sourceCell.column, sourceCell.row);
                if (!existsSync(input)) {
                    throw new Error(`missing source radar tile ${input}`);
                }
                copyFileSync(input, output);
                tiles.push({
                    path: relative,
                    column,
                    row,
                    source: basename(input),
                });
                continue;
            }

            const rgba = new Uint8Array(TILE_SIZE * TILE_SIZE * 4);
            for (let y = 0; y < TILE_SIZE; y++) {
                for (let x = 0; x < TILE_SIZE; x++) {
                    const destinationWorldX =
                        DESTINATION_WORLD_MIN + column * CELL_WORLD_SIZE + (x + 0.5) * PIXEL_WORLD_SIZE;
                    const destinationWorldY =
                        -DESTINATION_WORLD_MIN - row * CELL_WORLD_SIZE - (y + 0.5) * PIXEL_WORLD_SIZE;
                    const sourceWorldX = destinationWorldX - map.translationX;
                    const sourceWorldY = destinationWorldY - map.translationY;
                    const sourcePixelX = (sourceWorldX - SOURCE_WORLD_MIN) / PIXEL_WORLD_SIZE - 0.5;
                    const sourcePixelY = (-SOURCE_WORLD_MIN - sourceWorldY) / PIXEL_WORLD_SIZE - 0.5;

                    const x0 = Math.floor(sourcePixelX);
                    const y0 = Math.floor(sourcePixelY);
                    const xFraction = sourcePixelX - x0;
                    const yFraction = sourcePixelY - y0;
                    const x1 = x0 + 1;
                    const y1 = y0 + 1;

                    function getPixel(globalX, globalY) {
                        const sourceColumn = Math.floor(globalX / TILE_SIZE);
                        const sourceRow = Math.floor(globalY / TILE_SIZE);
                        const localX = ((globalX % TILE_SIZE) + TILE_SIZE) % TILE_SIZE;
                        const localY = ((globalY % TILE_SIZE) + TILE_SIZE) % TILE_SIZE;
                        return pixelFromTile(loadSource(sourceColumn, sourceRow), localX, localY);
                    }

                    const top = interpolate(getPixel(x0, y0), getPixel(x1, y0), xFraction);
                    const pixel =
                        yFraction < 1e-9
                            ? top
                            : interpolate(
                                  top,
                                  interpolate(getPixel(x0, y1), getPixel(x1, y1), xFraction),
                                  yFraction,
                              );
                    const offset = (y * TILE_SIZE + x) * 4;
                    rgba.set(pixel, offset);
                }
            }

            const writer = new TXDWriter(undefined, "dxt1");
            writer.addTexture(`radar_${key}_${column}_${row}`, TILE_SIZE, TILE_SIZE, rgba);
            writeFileSync(output, new Uint8Array(writer.write()));
            tiles.push({
                path: relative,
                column,
                row,
                source: `UG grid translated ${map.translationX},${map.translationY}`,
            });
        }
    }

    writeManifest(resource, map, tiles);
    updateMeta(resource, tiles);
    const bytes = tiles.reduce((sum, tile) => sum + readFileSync(join(resource, tile.path)).length, 0);
    console.log(
        `${map.resourceName}: ${tiles.length} tiles, columns ${map.columns[0]}..${map.columns[1]}, ` +
            `rows ${map.rows[0]}..${map.rows[1]}, ${(bytes / 1024 / 1024).toFixed(1)} MiB`,
    );
}

async function main() {
    const options = parseArguments();
    const readerModule = await import(pathToFileURL(join(options["txd-tools"], "TXDReader.js")));
    const writerModule = await import(pathToFileURL(join(options["txd-tools"], "TXDWriter.js")));
    const maps = options.map ? [[options.map, MAPS[options.map]]] : Object.entries(MAPS);
    for (const [key, map] of maps) {
        await buildMap(options, key, map, readerModule.TXDReader, writerModule.TXDWriter);
    }
}

main().catch((error) => {
    console.error(error.stack || error.message);
    process.exitCode = 1;
});
