#!/usr/bin/env python3
"""Extract and relocate complete Carcer City radar tiles from the demo."""

from __future__ import annotations

import argparse
import shutil
import struct
import zipfile
from dataclasses import dataclass
from pathlib import Path


ARCHIVE_ROOT = "GTA Carcer City Demo/"
IMG_PATH = ARCHIVE_ROOT + "models/gta3.img"
SECTOR_SIZE = 2048
DIRECTORY_ENTRY = struct.Struct("<IHH24s")

# The combined Clarksland and Lac Point exterior occupies these cells before
# the resource's +6000 X translation. Keeping the exact 500-unit source cells
# avoids any resampling of the supplied radar artwork. Rows decrease while
# world Y increases in GTA's radar grid.
SOURCE_COLUMNS = range(16, 23)
SOURCE_ROWS = range(15, 24)
TRANSLATION_X = 6000
TRANSLATION_Y = 0


@dataclass(frozen=True)
class ImgEntry:
    name: str
    offset: int
    size: int


def radar_name(column: int, row: int) -> str:
    local_column = column - 14
    local_row = row - 14
    if not 0 <= local_column < 12 or not 0 <= local_row < 12:
        raise ValueError(f"source cell {column},{row} is outside the stock 12x12 radar grid")
    return f"radar{local_row * 12 + local_column:02d}.txd"


def read_img_directory(stream) -> dict[str, ImgEntry]:
    header = stream.read(8)
    if len(header) != 8 or header[:4] != b"VER2":
        raise ValueError("expected a GTA IMG v2 archive")
    count = struct.unpack_from("<I", header, 4)[0]
    directory = stream.read(count * DIRECTORY_ENTRY.size)
    if len(directory) != count * DIRECTORY_ENTRY.size:
        raise ValueError("truncated GTA IMG directory")

    entries: dict[str, ImgEntry] = {}
    for index in range(count):
        offset = index * DIRECTORY_ENTRY.size
        sector, streaming_sectors, archive_sectors, raw_name = DIRECTORY_ENTRY.unpack_from(directory, offset)
        name = raw_name.split(b"\0", 1)[0].decode("ascii", errors="strict").casefold()
        sectors = archive_sectors or streaming_sectors
        entries[name] = ImgEntry(name, sector * SECTOR_SIZE, sectors * SECTOR_SIZE)
    return entries


def write_lua_manifest(output: Path, tiles: list[tuple[str, int, int, str]]) -> None:
    lines = ["-- Generated by utils/extended-world/extract_carcer_radar.py.", "CARCER_RADAR_TILES = {"]
    for path, column, row, source in tiles:
        lines.append(f'    {{ path = "{path}", column = {column}, row = {row}, source = "{source}" }},')
    lines.extend(("}", ""))
    (output / "radar_tiles.lua").write_text("\n".join(lines), encoding="utf-8")


def update_meta(output: Path, tiles: list[tuple[str, int, int, str]]) -> None:
    meta_path = output / "meta.xml"
    text = meta_path.read_text(encoding="utf-8")
    script = '    <script src="radar_tiles.lua" type="client" cache="false" />'
    if script not in text:
        anchor = '    <script src="map_data.lua" type="client" cache="false" />'
        if anchor not in text:
            raise ValueError(f"cannot find map_data.lua in {meta_path}")
        text = text.replace(anchor, anchor + "\n" + script)

    lines = [line for line in text.splitlines() if '<file src="assets/radar/' not in line]
    closing_index = lines.index("</meta>")
    radar_files = [f'    <file src="{tile[0]}" />' for tile in tiles]
    lines[closing_index:closing_index] = radar_files
    meta_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--archive", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True, help="Carcer MTA resource directory")
    args = parser.parse_args()

    if TRANSLATION_X % 500 or TRANSLATION_Y % 500:
        raise ValueError("direct radar relocation requires translations aligned to 500 world units")
    column_delta = TRANSLATION_X // 500
    row_delta = -(TRANSLATION_Y // 500)

    requested: dict[str, tuple[int, int]] = {}
    for row in SOURCE_ROWS:
        for column in SOURCE_COLUMNS:
            requested[radar_name(column, row)] = (column + column_delta, row + row_delta)

    radar_output = args.output / "assets" / "radar"
    if radar_output.exists():
        shutil.rmtree(radar_output)
    radar_output.mkdir(parents=True)

    tiles: list[tuple[str, int, int, str]] = []
    with zipfile.ZipFile(args.archive) as archive:
        with archive.open(IMG_PATH) as image:
            entries = read_img_directory(image)
            selected = []
            for name, destination in requested.items():
                entry = entries.get(name)
                if entry is None:
                    raise FileNotFoundError(f"{name} is missing from {IMG_PATH}")
                selected.append((entry, destination))

            # ZipExtFile seeking is cheapest in ascending order because the IMG
            # itself is deflated inside the outer ZIP.
            for entry, (column, row) in sorted(selected, key=lambda value: value[0].offset):
                image.seek(entry.offset)
                data = image.read(entry.size)
                if len(data) != entry.size or data[:4] != b"\x16\0\0\0":
                    raise ValueError(f"invalid or truncated TXD entry {entry.name}")
                relative = f"assets/radar/tile_{column:02d}_{row:02d}.txd"
                (args.output / relative).write_bytes(data)
                tiles.append((relative, column, row, entry.name))

    tiles.sort(key=lambda value: (value[2], value[1]))
    write_lua_manifest(args.output, tiles)
    update_meta(args.output, tiles)
    total_bytes = sum((args.output / tile[0]).stat().st_size for tile in tiles)
    print(f"extracted {len(tiles)} Carcer City radar tiles ({total_bytes / (1024 * 1024):.1f} MiB)")
    print(f"destination columns {min(tile[1] for tile in tiles)}..{max(tile[1] for tile in tiles)}, "
          f"rows {min(tile[2] for tile in tiles)}..{max(tile[2] for tile in tiles)}")


if __name__ == "__main__":
    main()
