-- Generated by utils/extended-world/build_ug_radar.mjs.
UG_BW_RADAR_TILES = {
    { path = "assets/radar/tile_01_03.txd", column = 1, row = 3, source = "radar1790.txd" },
    { path = "assets/radar/tile_02_03.txd", column = 2, row = 3, source = "radar1791.txd" },
    { path = "assets/radar/tile_03_03.txd", column = 3, row = 3, source = "radar1792.txd" },
    { path = "assets/radar/tile_04_03.txd", column = 4, row = 3, source = "radar1793.txd" },
    { path = "assets/radar/tile_05_03.txd", column = 5, row = 3, source = "radar1794.txd" },
    { path = "assets/radar/tile_01_04.txd", column = 1, row = 4, source = "radar1886.txd" },
    { path = "assets/radar/tile_02_04.txd", column = 2, row = 4, source = "radar1887.txd" },
    { path = "assets/radar/tile_03_04.txd", column = 3, row = 4, source = "radar1888.txd" },
    { path = "assets/radar/tile_04_04.txd", column = 4, row = 4, source = "radar1889.txd" },
    { path = "assets/radar/tile_05_04.txd", column = 5, row = 4, source = "radar1890.txd" },
    { path = "assets/radar/tile_01_05.txd", column = 1, row = 5, source = "radar1982.txd" },
    { path = "assets/radar/tile_02_05.txd", column = 2, row = 5, source = "radar1983.txd" },
    { path = "assets/radar/tile_03_05.txd", column = 3, row = 5, source = "radar1984.txd" },
    { path = "assets/radar/tile_04_05.txd", column = 4, row = 5, source = "radar1985.txd" },
    { path = "assets/radar/tile_05_05.txd", column = 5, row = 5, source = "radar1986.txd" },
}
